### ISSUE TITLE
Non-center blocks in 3x3 breaks do not respect harvest levels

### ISSUE THREAD

**Issue by RayzoRayy** [astradamus/PracticalTools#3]
Looked at some of your code for the Hammer. If your using this with vanilla, there will be no problems at all since Iron can mine diamond ore, but if your using this mod with another mod that ads an ore with a harvest level of 4, your hammers dont check for harvest levels, it doesn't look like they do anyways for the surrounding blocks from the middle one you mine. Know what I mean? So if your mining with an Iron hammer say, and you come across say some Cobalt Ore for example, and its a harvest level of 4, if you mine the middle block of the 3x3, and the cobalt ore is apart of that 3x3 radius, its not going to check the harvest level for those blocks, so itll just mine the cobalt ore regardless and drop whatever the cobalt ore would drop. (just using this as an example). I think you need to implement some kind of harvest level checker for the 3x3 blocks it mines around the block that you actually target/mine(the middle of the 3x3). Hopefully you understand what im trying to say. :D

**Comment by astradamus** [comment]
I think I follow you. You're saying the center (targeted) block will fail to produce cobalt but the adjacent blocks would produce drops?

**Comment by astradamus** [comment]
Hmm does this mean iron hammers can collect obsidian from non-center blocks?

**Comment by astradamus** [comment]
Just tested. Iron Hammers can indeed collect Obsidian from non-center blocks. That's bad! Thanks for pointing this out.

**Comment by RayzoRayy** [comment]
:) Yeah sorry I wasn't too sure how to explain it, I guess I shoulda said the surrounding 8 blocks don't have a harvest level checker for the type of hammer you are using lol. Glad you know what I mean now tho. :D
