### ISSUE TITLE
Greataxe crashes server on gathering wood 1.14.4

### ISSUE THREAD

**Issue by ar7max** [astradamus/PracticalTools#6]
1.14.4 + Forge + Optifine

When first wood block breaks it freezes whole client and crashes 

[latest.log](https://pastebin.com/0UQckdxr)

**Comment by astradamus** [comment]
Sorry for the *rather* late response, which version of Practical Tools were you using? I believe this was fixed by 1.4 so I suspect you are using 1.3b? I'm going to close this issue on the assumption that you are not coming back but if you do still have the issue say so here and I'll investigate :)
