### ISSUE TITLE
Storage drawers lose their inventory when indirectly chopped with greataxe

### ISSUE THREAD

**Issue by Z0rdak** [astradamus/PracticalTools#8]
# Version Information

Forge version: 28.1.96
Practical Tools version: 1.14.4-1.4
Storage Drawers version: 1.14.4-6.0.5

# Further Information

Steps to reproduce:

   *    Use a greataxe of any kind (Iron, Gold, Diamond)
   *    Chop a wood block beside a wooden (filled) storage drawer container

## What I expected to happen:
The storage drawers keep their inventory, no matter if they are dismantled directly or indirectly through the 3x3 radius of the axe.

## What happened instead:
The drawers, which are indirectly removed by the axe, lose their inventory.

## Gif demonstrating the issue
![practical-tools-drawers-issue](https://user-images.githubusercontent.com/18328939/72142416-e944d480-3394-11ea-9dc6-4e84aec562fd.gif)

Edit: This also happens with the hammers and the compacting stone drawers.
(I assume the tools do not consider the nbt data of the blocks that are indirectly broken?)

**Comment by astradamus** [comment]
Wow! This bug report is incredible, very well presented!

I am working on this mod again so I'll look into this, not sure if you still care lol. My first impression is that this is a problem with the way Storage Drawers is handling breaking/dropping. The indirect breaks aren't doing anything particularly weird and the blocks being broken shouldn't "know the difference" so to speak. I'm guessing Storage Drawers does something weird to enable the storage-through-break functionality. I will look into it and figure out why it isn't triggering on the indirects.

**Comment by Z0rdak** [comment]
Hey there! Great to hear that you are still working on this mod. I almost forgot about this issue to be honest. 

I hope my description is helpful. I am a java developer myself and I am always happy if someone shares a detailed description to reproduce an issue. 

Sadly i am not familiar with minecraft modding so i am unsure whether this belongs here or is a storage drawer issue.

Anyway good luck and thanks for the work!

**Comment by astradamus** [comment]
Thanks for bringing this to my attention, in the process of investigating it I actually discovered several more bugs and a huge fundamental flaw in the way the mod was handling the area of effect block breaks. That's all fixed now! :)

**Comment by Z0rdak** [comment]
Awesome! Glad to hear! :+1: 
Time to add it to my 1.15.2 modpack, again. :)

**Comment by astradamus** [comment]
Ah, the 1.15.2 version I posted still has the bug, I'll see about releasing a fix for that version later, should, should be easy.

**Comment by astradamus** [comment]
It's done! The changes have been backported to 1.14.4 AND 1.15.2 :)
